/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'id' : AnnouncementId,
  'content' : string,
  'timestamp' : bigint,
}
export type AnnouncementId = bigint;
export interface ClassInfo { 'year' : bigint, 'className' : string }
export interface Comment {
  'content' : string,
  'author' : Principal,
  'timestamp' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface Message {
  'id' : MessageId,
  'content' : string,
  'read' : boolean,
  'sender' : Principal,
  'timestamp' : bigint,
  'receiver' : Principal,
}
export type MessageId = bigint;
export interface Notification {
  'id' : NotificationId,
  'content' : string,
  'read' : boolean,
  'user' : Principal,
  'timestamp' : bigint,
}
export type NotificationId = bigint;
export interface Post {
  'id' : PostId,
  'media' : [] | [ExternalBlob],
  'content' : string,
  'author' : Principal,
  'likes' : bigint,
  'timestamp' : bigint,
  'comments' : Array<Comment>,
}
export type PostId = bigint;
export interface Story {
  'id' : StoryId,
  'content' : string,
  'author' : Principal,
  'timestamp' : bigint,
  'image' : [] | [ExternalBlob],
}
export type StoryId = bigint;
export interface UserProfile {
  'id' : Principal,
  'bio' : string,
  'firstRegistered' : boolean,
  'name' : string,
  'role' : UserRole,
  'profilePicture' : [] | [ExternalBlob],
  'classInfo' : ClassInfo,
  'lastSeen' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'owner' : null } |
  { 'user' : null } |
  { 'banned' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignAdminRole' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'banUser' : ActorMethod<[Principal], undefined>,
  'commentOnPost' : ActorMethod<[PostId, string], undefined>,
  'createAnnouncement' : ActorMethod<[string], Announcement>,
  'createPost' : ActorMethod<[string, [] | [ExternalBlob]], Post>,
  'createStory' : ActorMethod<[string, [] | [ExternalBlob]], Story>,
  'deletePost' : ActorMethod<[PostId], undefined>,
  'getActiveStories' : ActorMethod<[], Array<Story>>,
  'getActivityStats' : ActorMethod<
    [],
    {
      'activeUsers' : bigint,
      'totalMessages' : bigint,
      'totalUsers' : bigint,
      'totalPosts' : bigint,
    }
  >,
  'getAllPosts' : ActorMethod<[], Array<Post>>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getConversation' : ActorMethod<[Principal], Array<Message>>,
  'getConversations' : ActorMethod<[], Array<[Principal, Message]>>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getPostsByUser' : ActorMethod<[Principal], Array<Post>>,
  'getRoleBadge' : ActorMethod<[Principal], UserRole>,
  'getUnreadNotificationCount' : ActorMethod<[], bigint>,
  'getUser' : ActorMethod<[Principal], UserProfile>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likePost' : ActorMethod<[PostId], undefined>,
  'markMessageAsRead' : ActorMethod<[MessageId], undefined>,
  'markNotificationAsRead' : ActorMethod<[NotificationId], undefined>,
  'removeAdminRole' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchUsers' : ActorMethod<[string], Array<UserProfile>>,
  'sendMessage' : ActorMethod<[Principal, string], Message>,
  'signup' : ActorMethod<[string, string, bigint], undefined>,
  'unbanUser' : ActorMethod<[Principal], undefined>,
  'updateLastSeen' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];